@startuml
!includeurl https://raw.githubusercontent.com/luudvkeulen/PlantUMLISStijl/master/design.puml

Title Activity diagram

start
:Actie 1;

:Actie 2;

:Actie 3;

if (Statement) then (ja)
    :Ja actie;
else (nee)
    :Nee actie;
endif

:Actie 4;

stop
@enduml