@startuml
!includeurl https://raw.githubusercontent.com/luudvkeulen/PlantUMLISStijl/master/remoteindex.puml

Title Sequence diagram
actor actor1 as a1 
participant participant1 as p1
participant participant2 as p2 

request(a1, p2, request 1)
return(p2, a1, return message for request 1)
request(a1, p1, request 2)
self(p1, validate request 2)

@enduml